name: build

on: 
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**cd.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install webkit2gtk for Tauri
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. '0.9.1', 'latest')
        version: 'latest'
    - name: Build
      run: |
        cp .env.example .env
        npm run install
        npm run build
    - name: cargo fmt & clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy -- --deny=warnings
